<?php

namespace Database\Seeders;

use App\Models\Dosen;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Str;

class DosenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        //Dosen Sistem Informasi SI
        $initialData = [
            [
                'nidn' => '2001087503',
                'nip' => '19750801 200912 2 001',
                'nama' => 'Gusmelia Testiana, M.Kom.',
                'no_hp' => null,
                'alamat' => null,
                'tempat_tanggal_lahir' => 'Maninjau, 01-08-1975',
                'pangkat' => 'Penata Tk.1',
                'golongan' => 'III.d',
                'tmt_fst' => Carbon::createFromFormat('d/m/Y', '10/6/2016'),
                'jabatan' => 'Ka Prodi/Dosen/Lektor',
                'status' => 'aktif',
                'prodi_id' => 1,
                'foto' => null,
            ],
            [
                'nidn' => '2022117502',
                'nip' => '19751122 200604 1 003',
                'nama' => 'Ruliansyah, S.T., M.Kom.',
                'no_hp' => null,
                'alamat' => null,
                'tempat_tanggal_lahir' => 'Palembang, 22-11-1975',
                'pangkat' => 'Penata Tk.1',
                'golongan' => 'III.d',
                'tmt_fst' => Carbon::createFromFormat('d/m/Y', '2/1/2017'),
                'jabatan' => 'Dosen / Lektor',
                'status' => 'aktif',
                'prodi_id' => 1,
                'foto' => null,
            ],
            [
                'nidn' => '2007116701',
                'nip' => '19671107 199803 2 001',
                'nama' => 'Dr. Fenny Purwani, M.Kom.',
                'no_hp' => null,
                'alamat' => null,
                'tempat_tanggal_lahir' => 'Yogyakarta, 07-11-1967',
                'pangkat' => 'Penata Tk.1',
                'golongan' => 'III.d',
                'tmt_fst' => Carbon::createFromFormat('d/m/Y', '2/1/2017'),
                'jabatan' => 'Dosen / Lektor',
                'status' => 'aktif',
                'prodi_id' => 1,
                'foto' => null,
                'override_firstname' => 'fenny' // Tambahan untuk override firstname karena ada nama depan yang sama
            ],
            [
                'nidn' => '2025117901',
                'nip' => '19791125 201403 2 002',
                'nama' => 'RUSMALA SANTI, M.Kom.',
                'no_hp' => null,
                'alamat' => null,
                'tempat_tanggal_lahir' => 'Muba, 25-11-1979',
                'pangkat' => 'Penata Muda Tk.1',
                'golongan' => 'III.b',
                'tmt_fst' => Carbon::createFromFormat('d/m/Y', '2/1/2017'),
                'jabatan' => 'Dosen / Lektor',
                'status' => 'aktif',
                'prodi_id' => 1,
                'foto' => null,
            ],
            [
                'nidn' => '2003058601',
                'nip' => '19860503 201903 1 009',
                'nama' => 'Catur Eri Gunawan, S.T., M.Cs.',
                'no_hp' => null,
                'alamat' => null,
                'tempat_tanggal_lahir' => 'Palembang, 03-05-1986',
                'pangkat' => 'Penata Muda Tk.1',
                'golongan' => 'III.d',
                'tmt_fst' => Carbon::createFromFormat('d/m/Y', '3/1/2019'),
                'jabatan' => 'Dosen / Lektor',
                'status' => 'aktif',
                'prodi_id' => 1,
                'foto' => null,
            ],
            [
                'nidn' => '0208018701',
                'nip' => '19870108 202012 1 009',
                'nama' => 'Irfan Dwi Jaya, M.Kom.',
                'no_hp' => null,
                'alamat' => null,
                'tempat_tanggal_lahir' => 'Palembang, 08-01-1987',
                'pangkat' => 'Penata Muda Tk.1',
                'golongan' => 'III.b',
                'tmt_fst' => Carbon::createFromFormat('d/m/Y', '12/1/2020'),
                'jabatan' => 'Dosen / Asisten Ahli',
                'status' => 'aktif',
                'prodi_id' => 1,
                'foto' => null,
            ],
            [
                'nidn' => '0214118701',
                'nip' => '19871114 202321 1 026',
                'nama' => 'Fenando, M.Kom.',
                'no_hp' => null,
                'alamat' => null,
                'tempat_tanggal_lahir' => 'Palembang, 14-11-1987',
                'pangkat' => 'PPPK',
                'golongan' => 'III.d',
                'tmt_fst' => Carbon::createFromFormat('d/m/Y', '2/1/2017'),
                'jabatan' => 'Dosen / Lektor',
                'status' => 'aktif',
                'prodi_id' => 1,
                'foto' => null,
            ],
            [
                'nidn' => '0203118601',
                'nip' => 203118601,
                'nama' => 'Freddy Kurnia Wijaya, S.Kom., M.Eng.',
                'no_hp' => null,
                'alamat' => null,
                'tempat_tanggal_lahir' => 'Sarolangun Jambi, 03-11-1986',
                'pangkat' => 'Non ASN',
                'golongan' => 'III.b',
                'tmt_fst' => Carbon::createFromFormat('d/m/Y', '2/1/2017'),
                'jabatan' => 'Dosen / Asisten Ahli',
                'status' => 'aktif',
                'prodi_id' => 1,
                'foto' => null,
            ],
            [
                'nidn' => '0215108502',
                'nip' => '19851015 202521 2 005',
                'nama' => 'Evi Fadilah, M.Kom.',
                'no_hp' => null,
                'alamat' => null,
                'tempat_tanggal_lahir' => 'Palembang, 15-10-1985',
                'pangkat' => 'PPPK',
                'golongan' => 'III.c',
                'tmt_fst' => Carbon::createFromFormat('d/m/Y', '2/1/2017'),
                'jabatan' => 'Dosen / Lektor',
                'status' => 'aktif',
                'prodi_id' => 1,
                'foto' => null,
            ],
            [
                'nidn' => '0223108404',
                'nip' => '19841023 202321 1 016',
                'nama' => 'Muhamad Kadafi, M.Kom.',
                'no_hp' => null,
                'alamat' => null,
                'tempat_tanggal_lahir' => 'Palembang, 23-10-1984',
                'pangkat' => 'PPPK',
                'golongan' => 'III.c',
                'tmt_fst' => Carbon::createFromFormat('d/m/Y', '2/1/2017'),
                'jabatan' => 'Dosen / Lektor',
                'status' => 'aktif',
                'prodi_id' => 1,
                'foto' => null,
                'override_firstname' => 'kadafi' // Tambahan untuk override firstname karena ada nama depan yang sama
            ],
            [
                'nidn' => '2029128503',
                'nip' => '19851229 202321 1 020',
                'nama' => 'Muhamad Son Muarie, M.Kom.',
                'no_hp' => null,
                'alamat' => null,
                'tempat_tanggal_lahir' => 'Lumpatan, 29-12-1985',
                'pangkat' => 'PPPK',
                'golongan' => 'III.b',
                'tmt_fst' => Carbon::createFromFormat('d/m/Y', '1/1/2018'),
                'jabatan' => 'Dosen / Asisten Ahli',
                'status' => 'aktif',
                'prodi_id' => 1,
                'foto' => null,
                'override_firstname' => 'son' // Tambahan untuk override firstname karena ada nama depan yang sama
            ],
            [
                'nidn' => '2017118205',
                'nip' => '19821117 202321 2 021',
                'nama' => 'Fathiyah Nopriani, S.T., M.Kom.',
                'no_hp' => null,
                'alamat' => null,
                'tempat_tanggal_lahir' => 'Palembang, 17-11-1982',
                'pangkat' => 'PPPK',
                'golongan' => 'III.c',
                'tmt_fst' => Carbon::createFromFormat('d/m/Y', '1/1/2018'),
                'jabatan' => 'Sekprodi/Dosen/Lektor',
                'status' => 'aktif',
                'prodi_id' => 1,
                'foto' => null,
            ],
            [
                'nidn' => '2021128901',
                'nip' => '19891221 202321 1 018',
                'nama' => 'Imamulhakim Syahid Putra, M.Kom.',
                'no_hp' => null,
                'alamat' => null,
                'tempat_tanggal_lahir' => 'Jaksel, 21-12-1989',
                'pangkat' => 'PPPK',
                'golongan' => 'III.b',
                'tmt_fst' => Carbon::createFromFormat('d/m/Y', '1/1/2018'),
                'jabatan' => 'Dosen / Asisten Ahli',
                'status' => 'aktif',
                'prodi_id' => 1,
                'foto' => null,
            ],
            [
                'nidn' => '2010098902',
                'nip' => '19890910 202321 1 028',
                'nama' => 'Aminullah Imal Alfresi, S.T., M.Kom.',
                'no_hp' => null,
                'alamat' => null,
                'tempat_tanggal_lahir' => 'Belitang, 10-09-1989',
                'pangkat' => 'PPPK',
                'golongan' => 'III.b',
                'tmt_fst' => Carbon::createFromFormat('d/m/Y', '1/1/2018'),
                'jabatan' => 'Dosen / Asisten Ahli',
                'status' => 'aktif',
                'prodi_id' => 1,
                'foto' => null,
            ],
            [
                'nidn' => '2004049101',
                'nip' => '19910104 202321 2 041',
                'nama' => 'Sri Rahayu, M.Kom.',
                'no_hp' => null,
                'alamat' => null,
                'tempat_tanggal_lahir' => 'Palembang, 04-01-1991',
                'pangkat' => 'PPPK',
                'golongan' => 'III.b',
                'tmt_fst' => Carbon::createFromFormat('d/m/Y', '1/1/2018'),
                'jabatan' => 'Dosen / Asisten Ahli',
                'status' => 'aktif',
                'prodi_id' => 1,
                'foto' => null,
            ],
            [
                'nidn' => '2030129301',
                'nip' => '19931230 202321 1 017',
                'nama' => 'M. Leandry Dalafranka, S.SI., M.Kom.',
                'no_hp' => null,
                'alamat' => null,
                'tempat_tanggal_lahir' => 'Palembang, 30-12-1993',
                'pangkat' => 'PPPK',
                'golongan' => 'III.b',
                'tmt_fst' => Carbon::createFromFormat('d/m/Y', '5/2/2019'),
                'jabatan' => 'Dosen / Asisten Ahli',
                'status' => 'aktif',
                'prodi_id' => 1,
                'foto' => null,
                'override_firstname' => 'leandry' // Tambahan untuk override firstname karena ada nama depan yang sama
            ],
            [
                'nidn' => '2023058902',
                'nip' => '198905232025212020',
                'nama' => 'Indah Hidayanti, S.T., M.Kom.',
                'no_hp' => null,
                'alamat' => null,
                'tempat_tanggal_lahir' => 'Palembang, 23-05-1989',
                'pangkat' => 'PPPK',
                'golongan' => 'III.b',
                'tmt_fst' => Carbon::createFromFormat('d/m/Y', '22/11/2021'),
                'jabatan' => 'Dosen / Asisten Ahli',
                'status' => 'aktif',
                'prodi_id' => 1,
                'foto' => null,
            ],
            [
                'nidn' => '2009048801',
                'nip' => '19880904 202521 2 002',
                'nama' => 'Reni Septiyanti, S.SI., M.Kom.',
                'no_hp' => null,
                'alamat' => null,
                'tempat_tanggal_lahir' => 'Plaju, 04-09-1988',
                'pangkat' => 'PPPK',
                'golongan' => 'III.b',
                'tmt_fst' => Carbon::createFromFormat('d/m/Y', '22/11/2021'),
                'jabatan' => 'Dosen / Asisten Ahli',
                'status' => 'aktif',
                'prodi_id' => 1,
                'foto' => null,
            ],
            [
                'nidn' => '2030069402',
                'nip' => '19940630 202521 2 009',
                'nama' => 'Gina Agiyani, M.Kom.',
                'no_hp' => null,
                'alamat' => null,
                'tempat_tanggal_lahir' => 'Tanjung Batu, 30-06-1994',
                'pangkat' => 'PPPK',
                'golongan' => 'III.b',
                'tmt_fst' => Carbon::createFromFormat('d/m/Y', '22/11/2021'),
                'jabatan' => 'Dosen / Asisten Ahli',
                'status' => 'aktif',
                'prodi_id' => 1,
                'foto' => null,
            ],
            [
                'nidn' => '2013047902',
                'nip' => '19790403 202321 1 007',
                'nama' => 'M. Syendi Apriko, M.Kom.',
                'no_hp' => null,
                'alamat' => null,
                'tempat_tanggal_lahir' => 'Palembang, 13-04-1979',
                'pangkat' => 'PPPK',
                'golongan' => 'III.b',
                'tmt_fst' => Carbon::createFromFormat('d/m/Y', '1/1/2018'),
                'jabatan' => 'Dosen / Asisten Ahli',
                'status' => 'aktif',
                'prodi_id' => 1,
                'foto' => null,
                'override_firstname' => 'syendi' // Tambahan untuk override firstname karena ada nama depan yang sama
            ],
            [
                'nidn' => '0221039001',
                'nip' => '199003212024031001',
                'nama' => 'Deni Fikari, S.Kom., M.Kom.',
                'no_hp' => null,
                'alamat' => null,
                'tempat_tanggal_lahir' => 'Kab. Musi Banyuasin, 21 Maret 1990',
                'pangkat' => 'CPNS',
                'golongan' => 'III.b',
                'tmt_fst' => Carbon::createFromFormat('d/m/Y', '3/1/2024'),
                'jabatan' => 'Cados',
                'status' => 'aktif',
                'prodi_id' => 1,
                'foto' => null,
            ],
            [
                'nidn' => '2001027202',
                'nip' => '197202012000031004',
                'nama' => 'Dr. Muhammad Isnaini, M.Pd',
                'no_hp' => null,
                'alamat' => null,
                'tempat_tanggal_lahir' => null,
                'pangkat' => 'CPNS',
                'golongan' => 'III.b',
                'tmt_fst' => Carbon::createFromFormat('d/m/Y', '3/1/2020'),
                'jabatan' => 'Dekan',
                'status' => 'aktif',
                'prodi_id' => 1,
                'foto' => null,
                'override_firstname' => 'isnaini' // Tambahan untuk override firstname karena ada nama depan yang sama
            ],
            [
                'nidn' => '0002018705',
                'nip' =>'198701022018011001',
                'nama' => 'REZA ADE PUTRA, S.Pd, M.Cs',
                'no_hp' => null,
                'alamat' => null,
                'tempat_tanggal_lahir' => null,
                'pangkat' => 'CPNS',
                'golongan' => 'III.b',
                'tmt_fst' => Carbon::createFromFormat('d/m/Y', '3/1/2024'),
                'jabatan' => 'Cados',
                'status' => 'tidak aktif',
                'prodi_id' => 1,
                'foto' => null,
            ],
            [
                'nidn' => '2015128801',
                'nip' => '19881215 202321 1 005',
                'nama' => 'DIAN HAFIDH ZULFIKAR, S.Kom., M.Cs.',
                'no_hp' => null,
                'alamat' => null,
                'tempat_tanggal_lahir' => 'Palembang, 15-12-1988',
                'pangkat' => 'PPPK',
                'golongan' => 'III.b',
                'tmt_fst' => Carbon::createFromFormat('d/m/Y', '2/1/2017'),
                'jabatan' => 'Dosen / Asisten Ahli',
                'status' => 'aktif',
                'prodi_id' => 1,
                'foto' => null,
            ]
        ];

        foreach ($initialData as $data) {
            // Create user
            $firstName = $data['override_firstname'] ?? trim(string: Str::before(Str::before($data['nama'], ','), ' ')); // ambil kata pertama sebelum koma
            $nipNumbers = substr(preg_replace('/\D/', '', $data['nip']), 0, 8);
            $nipNim = Str::lower( $firstName . $nipNumbers);

            $user = User::create([
                'nip_nim' => $nipNim,
                'nama' => $data['nama'],
                'email' => $nipNim . '@radenfatah.ac.id',
                'password' => bcrypt($nipNim),
                'prodi_id' => $data['prodi_id']
            ]);

            // Assign role
            $user->assignRole('dosen');

            // Create mahasiswa with all required fields
            Dosen::create([
                'nidn' => $data['nidn'],
                'nip' => $data['nip'],
                'nama' => $data['nama'],
                'no_hp' => $data['no_hp'],
                'alamat' => $data['alamat'] ?? 'Palembang',
                'tempat_tanggal_lahir' => $data['tempat_tanggal_lahir'],
                'pangkat' => $data['pangkat'],
                'golongan' => $data['golongan'],
                'tmt_fst' => $data['tmt_fst'],
                'jabatan' => $data['jabatan'],
                'status' => $data['status'],
                'prodi_id' => $data['prodi_id'],
                'user_id' => $user->id,
                'foto' => $data['foto'],
            ]);
        }
    }
}
