<?php

namespace Database\Seeders;

use App\Models\Mahasiswa;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MahasiswaCoba extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $mahasiswaCoba = [
             [
                //1
                'nim' => '23041450085',
                'nama' => 'Muhammad Luqman Al-Fauzan',
                'no_hp' => '081234567890',
                'alamat' => 'Palembang',
                'prodi_id' => 1,
                'peminatan_id' => 1,
                'semester' => 5,
                'ipk' => 3.75,
                'dosen_pa' => 1,
                'pembimbing_1' => 3,
                'pembimbing_2' => 5,
                'status' => 'aktif',
                'angkatan' => '2023',
            ],
            [
                //2
                'nim' => '23041450086',
                'nama' => 'Farah Hasywaza Audremayna',
                'no_hp' => '081234567891',
                'prodi_id' => 1,
                'peminatan_id' => 2,
                'semester' => 5,
                'ipk' => 3.88,
                'dosen_pa' => 2,
                'pembimbing_1' => null,
                'pembimbing_2' => null,
                'status' => 'aktif',
                'angkatan' => '2023',
            ],
            [
                //3
                'nim' => '23041450087',
                'nama' => 'Rizki Faruli',
                'no_hp' => '081234567892',
                'prodi_id' => 1,
                'peminatan_id' => 1,
                'semester' => 5,
                'ipk' => 3.50,
                'dosen_pa' => 3,
                'pembimbing_1' => null,
                'pembimbing_2' => null,
                'status' => 'aktif',
                'angkatan' => '2023',
            ],
            [
                //4
                'nim' => '23051450228',
                'nama' => 'Muhammad Naufal',
                'no_hp' => '081234567893',
                'prodi_id' => 1,
                'peminatan_id' => 1,
                'semester' => 5,
                'ipk' => 3.60,
                'dosen_pa' => 4,
                'pembimbing_1' => null,
                'pembimbing_2' => null,
                'status' => 'aktif',
                'angkatan' => '2023',
            ],
            [
                //5
                'nim' => '23051450209',
                'nama' => 'KGS Moch Fauzan',
                'no_hp' => '081234567894',
                'prodi_id' => 1,
                'peminatan_id' => 1,
                'semester' => 5,
                'ipk' => 3.70,
                'dosen_pa' => 5,
                'pembimbing_1' => null,
                'pembimbing_2' => null,
                'status' => 'aktif',
                'angkatan' => '2023',
            ],
            [
                //6
                'nim' => '23051450167',
                'nama' => 'M.Agung',
                'no_hp' => '081234567895',
                'prodi_id' => 1,
                'peminatan_id' => 1,
                'semester' => 5,
                'ipk' => 3.2,
                'dosen_pa' => 6,
                'pembimbing_1' => null,
                'pembimbing_2' => null,
                'status' => 'aktif',
                'angkatan' => '2023',
            ],
            [
                //7
                'nim' => '23041450154',
                'nama' => 'Naufal',
                'no_hp' => '081234567896',
                'prodi_id' => 1,
                'peminatan_id' => 1,
                'semester' => 5,
                'ipk' => 3.90,
                'dosen_pa' => 7,
                'pembimbing_1' => null,
                'pembimbing_2' => null,
                'status' => 'aktif',
                'angkatan' => '2023',
            ],
            [
                //8
                'nim' => '23041450151',
                'nama' => 'Khalisha Alya Putri',
                'no_hp' => '081234567897',
                'prodi_id' => 1,
                'peminatan_id' => 3,
                'semester' => 5,
                'ipk' => 3.55,
                'dosen_pa' => 8,
                'pembimbing_1' => null,
                'pembimbing_2' => null,
                'status' => 'aktif',
                'angkatan' => '2023',
            ],
            [
                //9
                'nim' => '23051450176',
                'nama' => 'Nadhin Mutiara Hervani',
                'no_hp' => '081234567898',
                'prodi_id' => 1,
                'peminatan_id' => 3,
                'semester' => 5,
                'ipk' => 3.65,
                'dosen_pa' => 9,
                'pembimbing_1' => null,
                'pembimbing_2' => null,
                'status' => 'aktif',
                'angkatan' => '2023',
            ],
            [
                //10
                'nim' => '23051450174',
                'nama' => 'Istiqomah',
                'no_hp' => '081234567899',
                'prodi_id' => 1,
                'peminatan_id' => 3,
                'semester' => 5,
                'ipk' => 3.85,
                'dosen_pa' => 10,
                'pembimbing_1' => null,
                'pembimbing_2' => null,
                'status' => 'aktif',
                'angkatan' => '2023',
            ],
            [
                //11
                'nim' => '23041450071',
                'nama' => 'Deni Ardiansah',
                'no_hp' => '081234567892',
                'prodi_id' => 1,
                'peminatan_id' => 1,
                'semester' => 5,
                'ipk' => 3.50,
                'dosen_pa' => 11,
                'pembimbing_1' => null,
                'pembimbing_2' => null,
                'status' => 'aktif',
                'angkatan' => '2023',
            ],
            [
                //12
                'nim' => '23041450059',
                'nama' => 'Dhea Seni Permata',
                'no_hp' => '081234567891',
                'prodi_id' => 1,
                'peminatan_id' => 2,
                'semester' => 5,
                'ipk' => 3.88,
                'dosen_pa' => 12,
                'pembimbing_1' => null,
                'pembimbing_2' => null,
                'status' => 'aktif',
                'angkatan' => '2023',
            ],
            [
                //13
                'nim' => '23041450072',
                'nama' => 'Reki Kurniawan',
                'no_hp' => '081234567890',
                'prodi_id' => 1,
                'peminatan_id' => 1,
                'semester' => 5,
                'ipk' => 3.50,
                'dosen_pa' => 13,
                'pembimbing_1' => null,
                'pembimbing_2' => null,
                'status' => 'aktif',
                'angkatan' => '2023',
            ],
            [
                //14
                'nim' => '23041450078',
                'nama' => 'Dimas Prasetyo',
                'no_hp' => '081234567899',
                'prodi_id' => 1,
                'peminatan_id' => 1,
                'semester' => 5,
                'ipk' => 3.85,
                'dosen_pa' => 14,
                'pembimbing_1' => null,
                'pembimbing_2' => null,
                'status' => 'aktif',
                'angkatan' => '2023',
            ],
            [
                //15
                'nim' => '23041450068',
                'nama' => 'Fadly Rachmandani',
                'no_hp' => '081234567890',
                'prodi_id' => 1,
                'peminatan_id' => 1,
                'semester' => 5,
                'ipk' => 3.75,
                'dosen_pa' => 15,
                'pembimbing_1' => null,
                'pembimbing_2' => null,
                'status' => 'aktif',
                'angkatan' => '2023',
            ],
            [
                //16
                'nim' => '23041450063',
                'nama' => 'Muhammad Fahri Utama',
                'no_hp' => '081234567892',
                'prodi_id' => 1,
                'peminatan_id' => 1,
                'semester' => 5,
                'ipk' => 3.88,
                'dosen_pa' => 16,
                'pembimbing_1' => null,
                'pembimbing_2' => null,
                'status' => 'aktif',
                'angkatan' => '2023',
            ],
            [
                //17
                'nim' => '23041450065',
                'nama' => 'Tri Pama Juliyusriyyah',
                'no_hp' => '081234567893',
                'prodi_id' => 1,
                'peminatan_id' => 1,
                'semester' => 5,
                'ipk' => 3.50,
                'dosen_pa' => 17,
                'pembimbing_1' => null,
                'pembimbing_2' => null,
                'status' => 'aktif',
                'angkatan' => '2023',
            ],
            [
                //18
                'nim' => '23041450067',
                'nama' => 'Muhamad Zaki Ramadhan',
                'no_hp' => '081234567892',
                'prodi_id' => 1,
                'peminatan_id' => 1,
                'semester' => 5,
                'ipk' => 3.50,
                'dosen_pa' => 18,
                'pembimbing_1' => null,
                'pembimbing_2' => null,
                'status' => 'aktif',
                'angkatan' => '2023',
            ],
            [
                //19
                'nim' => '23041450110',
                'nama' => 'Alya Salsabilla',
                'no_hp' => '081234567892',
                'prodi_id' => 1,
                'peminatan_id' => 1,
                'semester' => 5,
                'ipk' => 3.50,
                'dosen_pa' => 19,
                'pembimbing_1' => null,
                'pembimbing_2' => null,
                'status' => 'aktif',
                'angkatan' => '2023',
            ],
            [
                //20
                'nim' => '23041450075',
                'nama' => 'M.Y Rama Wijaya',
                'no_hp' => '081234567892',
                'prodi_id' => 1,
                'peminatan_id' => 1,
                'semester' => 5,
                'ipk' => 3.50,
                'dosen_pa' => 20,
                'pembimbing_1' => null,
                'pembimbing_2' => null,
                'status' => 'aktif',
                'angkatan' => '2023',
            ],

            [
                //21
                'nim' => '2230803102',
                'nama' => 'Ade Kurniawan',
                'no_hp' => '081234567893',
                'prodi_id' => 1,
                'peminatan_id' => 2,
                'semester' => 7,
                'ipk' => 3.60,
                'dosen_pa' => 4,
                'pembimbing_1' => 2,
                'pembimbing_2' => 4,
                'status' => 'aktif',
                'angkatan' => '2022',
            ],

            [
                //22
                'nim' => '2230803147',
                'nama' => 'Ismi Melyana',
                'no_hp' => '081234567894',
                'prodi_id' => 1,
                'peminatan_id' => 3,
                'semester' => 7,
                'ipk' => 3.70,
                'dosen_pa' => 5,
                'pembimbing_1' => 5,
                'pembimbing_2' => 6,
                'status' => 'aktif',
                'angkatan' => '2022',
            ],

            [
                //23
                'nim' => '2230803095',
                'nama' => 'Berlia Nisyah',
                'no_hp' => '081234567895',
                'prodi_id' => 1,
                'peminatan_id' => 2,
                'semester' => 7,
                'ipk' => 3.80,
                'dosen_pa' => 6,
                'pembimbing_1' => 7,
                'pembimbing_2' => 8,
                'status' => 'aktif',
                'angkatan' => '2022',
            ],

            [
                //24
                'nim' => '2220803050',
                'nama' => 'Laila Indri Yani',
                'no_hp' => '081234567896',
                'prodi_id' => 1,
                'peminatan_id' => 1,
                'semester' => 7,
                'ipk' => 3.90,
                'dosen_pa' => 7,
                'pembimbing_1' => 9,
                'pembimbing_2' => 10,
                'status' => 'aktif',
                'angkatan' => '2022',
            ],
            [
                //25
                'nim' => '2220803079',
                'nama' => 'Aditya Surya Wiguna',
                'no_hp' => '081234567897',
                'prodi_id' => 1,
                'peminatan_id' => 2,
                'semester' => 7,
                'ipk' => 3.85,
                'dosen_pa' => 8,
                'pembimbing_1' => 11,
                'pembimbing_2' => 12,
                'status' => 'aktif',
                'angkatan' => '2022',
            ],
            [
                //26
                'nim' => '2220803068',
                'nama' => 'Eka Maisito',
                'no_hp' => '081234567898',
                'prodi_id' => 1,
                'peminatan_id' => 3,
                'semester' => 7,
                'ipk' => 3.75,
                'dosen_pa' => 9,
                'pembimbing_1' => 13,
                'pembimbing_2' => 14,
                'status' => 'aktif',
                'angkatan' => '2022',
            ],
            [
                //27
                'nim' => '2210803017',
                'nama' => 'Jeni Astuti',
                'no_hp' => '081234567899',
                'prodi_id' => 1,
                'peminatan_id' => 1,
                'semester' => 7,
                'ipk' => 3.65,
                'dosen_pa' => 10,
                'pembimbing_1' => 15,
                'pembimbing_2' => 16,
                'status' => 'aktif',
                'angkatan' => '2022',
            ],
            [
                //28
                'nim' => '2210803025',
                'nama' => 'Rizki Amalia',
                'no_hp' => '081234567890',
                'prodi_id' => 1,
                'peminatan_id' => 2,
                'semester' => 7,
                'ipk' => 3.55,
                'dosen_pa' => 11,
                'pembimbing_1' => 17,
                'pembimbing_2' => 18,
                'status' => 'aktif',
                'angkatan' => '2022',
            ],
            [
                //29
                'nim' => '2210803033',
                'nama' => 'Siti Nurhaliza',
                'no_hp' => '081234567891',
                'prodi_id' => 1,
                'peminatan_id' => 3,
                'semester' => 7,
                'ipk' => 3.95,
                'dosen_pa' => 12,
                'pembimbing_1' => 19,
                'pembimbing_2' => 20,
                'status' => 'aktif',
                'angkatan' => '2022',
            ],
            [
                //30
                'nim' => '2210803041',
                'nama' => 'Dewi Sartika',
                'no_hp' => '081234567892',
                'prodi_id' => 1,
                'peminatan_id' => 1,
                'semester' => 7,
                'ipk' => 3.45,
                'dosen_pa' => 13,
                'pembimbing_1' => 1,
                'pembimbing_2' => 2,
                'status' => 'aktif',
                'angkatan' => '2022',
            ],
        ];

        foreach ($mahasiswaCoba as $data) {
            // Create user
            $user = User::create([
                'nip_nim' => $data['nim'],
                'nama' => $data['nama'],
                'email' => $data['nim'] . '@radenfatah.ac.id',
                'password' => bcrypt($data['nim']),
                'prodi_id' => $data['prodi_id']
            ]);

            // Assign role
            $user->assignRole('mahasiswa');

            // Create mahasiswa with all required fields
            Mahasiswa::create([
                'nim' => $data['nim'],
                'nama' => $data['nama'],
                'no_hp' => $data['no_hp'],
                'alamat' => $data['alamat'] ?? 'Palembang',
                'semester' => $data['semester'],
                'ipk' => $data['ipk'],
                'prodi_id' => $data['prodi_id'],
                'peminatan_id' => $data['peminatan_id'],
                'user_id' => $user->id,
                'dosen_pa' => $data['dosen_pa'],
                'status' => $data['status'],
                'angkatan' => $data['angkatan'],
                'pembimbing_1' => $data['pembimbing_1'],
                'pembimbing_2' => $data['pembimbing_2'],
            ]);
        }
    }
}
